server:
  port: 8080
  servlet:
    context-path: /hrms
spring:
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/
    check-template-location: true
  datasource:
    username: root
    password: hlj172532
    url: jdbc:mysql://localhost:3306/hrms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    date-format: yyyy-MM-dd
    hiddenmethod:
      filter:
        enabled: true
  messages:
    basename: i18n.login

#整合mybatis
mybatis:
  type-aliases-package: com.ncu.hrms.bean
  mapper-locations: classpath:mapper/*.xml

#分页
pagehelper:
  auto-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql

